name:                algebraic-datatypes
version:             0.1.0.0
github:              "djrollins/haskell-from-first-principles"
license:             MIT
author:              "Daniel J. Rollins"
maintainer:          "daniel@djrollins.com"
copyright:           "2018 Daniel J. Rollins"

dependencies:
- base

library:
  source-dirs:
    - .
