name: haskell-from-first-principles
version: 0.1.0.0
github: "djrollins/haskell-from-first-prinicples"
license: MIT
author: "Daniel J. Rollins"
maintainer: "daniel@djrollins.com"
copyright: "2018 Daniel J. Rollins"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/djrollins/haskell-from-first-principles#readme>

dependencies:
  - base

library:
  source-dirs:
    - src/01-all-you-need-is-lambda/
    - src/02-hello-haskell/
    - src/03-strings/
    - src/04-basic-datatypes/
    - src/05-types/
    - src/06-typeclasses/
    - src/07-more-function-patterns/
    - src/08-recursion/
    - src/09-lists/
    - src/10-folding-lists/
  dependencies:
    - time
    - QuickCheck
