name: addition
version: 0.1.0.0
github: "djrollins/haskell-from-first-principles"
license: MIT
author: "Daniel J. Rollins"
maintainer: "daniel@djrollins.com"
category: Text

library:
  exposed-modules: Addition
  ghc-options: -Wall -fwarn-tabs
  dependencies:
    - base
    - hspec
  source-dirs: src
