name: morse
version: 0.1.0.0
github: "githubuser/morse"
license-file: LICENSE
author: "Daniel J. Rollins"
maintainer: "daniel@djrollins.com"
copyright: "2019 Daniel J. Rollins"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/morse#readme>

ghc-options:
  - -Wall
  - -fwarn-tabs

library:
  source-dirs: src
  exposed-modules: Morse
  dependencies:
    - base
    - containers

executable:
  main: Main.hs
  source-dirs: src
  dependencies:
    - base
    - containers
    - morse

tests:
  tests:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base
      - containers
      - morse
      - QuickCheck
